// src/config/siteConfig.ts

import { IconName } from "@/types/type.icon";

// Define the MenuItem type here and export it
export type MenuItem = {
  id?: string;
  menuId?: string;
  name: string; // Default name (English)
  module?: string;
  nameLang: Record<string, string>;
  href?: string;
  icon?: IconName;
  permissions?: {
    read: boolean;
    create: boolean;
    update: boolean;
    delete: boolean;
  };
  children?: MenuItem[];
  priority?: number;
  type?: string;
  active?: boolean;
};

// Export the siteConfig object
export const SiteConfig: MenuItem[] = [
  {
    active: true,
    children: [
      {
        active: true,
        href: "/home/dashboard",
        icon: "LayoutDashboard",
        id: "ADMIN_DASHBOARD_DASHBOARD",
        menuId: "ADMIN_DASHBOARD",
        name: "Dashboard",
        nameLang: {
          "en-US": "Dashboard",
          "hi-IN": "डैशबोर्ड",
          "kn-IN": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
          "ml-IN": "ഡാഷ്ബോർഡ്",
          "ta-IN": "டாஷ்போர்டு",
          "te-IN": "డాష్‌బోర్డ్",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/home/admin",
        icon: "ShieldCheck",
        id: "ADMIN_DASHBOARD_ADMIN",
        menuId: "ADMIN_DASHBOARD",
        name: "Admin",
        nameLang: {
          "en-US": "Admin",
          "hi-IN": "व्यवस्थापक",
          "kn-IN": "ನಿರ್ವಾಹಕ",
          "ml-IN": "അഡ്മിൻ",
          "ta-IN": "நிர்வாகி",
          "te-IN": "నిర్వాహకుడు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/home/user-activities",
        icon: "Activity",
        id: "ADMIN_DASHBOARD_USER_ACTIVITIES",
        menuId: "ADMIN_DASHBOARD",
        name: "User Activities",
        nameLang: {
          "en-US": "User Activities",
          "hi-IN": "उपयोगकर्ता गतिविधियाँ",
          "kn-IN": "ಬಳಕೆದಾರ ಚಟುವಟಿಕೆಗಳು",
          "ml-IN": "ഉപയോക്തൃ പ്രവർത്തനങ്ങൾ",
          "ta-IN": "பயனர் செயல்பாடுகள்",
          "te-IN": "వినియోగదారు కార్యకలాపాలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/support/chat",
        icon: "MessageCircle",
        id: "ADMIN_SUPPORT_CHATS",
        menuId: "ADMIN_SUPPORT",
        name: "Chats",
        nameLang: {
          "en-US": "User Chats",
          "hi-IN": "उपयोगकर्ता चैट",
          "kn-IN": "ಬಳಕೆದಾರ ಚಾಟ್‌ಗಳು",
          "ml-IN": "ഉപയോക്തൃ ചാറ്റുകൾ",
          "ta-IN": "பயனர் அரட்டைகள்",
          "te-IN": "వినియోగదారు చాట్లు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/reports/transactions",
        icon: "CreditCard",
        id: "ADMIN_REPORTS_TRANSACTIONS",
        menuId: "ADMIN_REPORTS",
        name: "Transactions",
        nameLang: {
          "en-US": "User Transactions",
          "hi-IN": "उपयोगकर्ता लेन-देन",
          "kn-IN": "ಬಳಕೆದಾರ ವಹಿವಾಟುಗಳು",
          "ml-IN": "ഉപയോക്തൃ ഇടപാടുകൾ",
          "ta-IN": "பயனர் பரிவர்த்தனைகள்",
          "te-IN": "వినియోగదారు లావాదేవీలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
    ],
    icon: "LayoutDashboard",
    id: "ADMIN_DASHBOARD",
    name: "Dashboard",
    nameLang: {
      "en-US": "Dashboard",
      "hi-IN": "डैशबोर्ड",
      "kn-IN": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
      "ml-IN": "ഡാഷ്ബോർഡ്",
      "ta-IN": "டாஷ்போர்டு",
      "te-IN": "డాష్‌బోర్డ్",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/profile/users",
        icon: "Users",
        id: "ADMIN_PROFILE_USERS",
        menuId: "ADMIN_PROFILE",
        name: "Users",
        nameLang: {
          "en-US": "Users",
          "hi-IN": "उपयोगकर्ता",
          "kn-IN": "ಬಳಕೆದಾರರು",
          "ml-IN": "ഉപയോക്താക്കൾ",
          "ta-IN": "பயனர்கள்",
          "te-IN": "వినియోగదారులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/profile/astrologers",
        icon: "Star",
        id: "ADMIN_PROFILE_ASTROLOGERS",
        menuId: "ADMIN_PROFILE",
        name: "Astrologers",
        nameLang: {
          "en-US": "Astrologers",
          "hi-IN": "ज्योतिषी",
          "kn-IN": "ಜ್ಯೋತಿಷಿಗಳು",
          "ml-IN": "ജ്യോതിഷികൾ",
          "ta-IN": "ஜோதிடர்கள்",
          "te-IN": "జ్యోతిష్కులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/profile/staff",
        icon: "CircleUser",
        id: "ADMIN_PROFILE_STAFF",
        menuId: "ADMIN_PROFILE",
        name: "Staff",
        nameLang: {
          "en-US": "Staff",
          "hi-IN": "स्टाफ़",
          "kn-IN": "ಸಿಬ್ಬಂದಿ",
          "ml-IN": "സ്റ്റാഫ്",
          "ta-IN": "பணியாளர்கள்",
          "te-IN": "సిబ్బంది",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
    ],
    icon: "UserStar",
    id: "ADMIN_PROFILE",
    name: "Profile",
    nameLang: {
      "en-US": "Profile",
      "hi-IN": "प्रोफ़ाइल",
      "kn-IN": "ಪ್ರೊಫೈಲ್",
      "ml-IN": "പ്രൊഫൈൽ",
      "ta-IN": "சுயவிவரம்",
      "te-IN": "ప్రొఫైల్",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/menu/menu-links",
        icon: "Link",
        id: "ADMIN_MENU_LINK",
        menuId: "ADMIN_MENU",
        name: "Menu Links",
        nameLang: {
          "en-US": "Menu Links",
          "hi-IN": "मेनू लिंक्स",
          "kn-IN": "ಮೆನು ಲಿಂಕ್ಸ್",
          "ml-IN": "മെനു ലിങ്കുകൾ",
          "ta-IN": "மெனு இணுப்புகள்",
          "te-IN": "మెనూ లింకులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/menu/menu-access",
        icon: "Key",
        id: "ADMIN_MENU_ACCESS",
        menuId: "ADMIN_MENU",
        name: "Menu Access",
        nameLang: {
          "en-US": "Menu Access",
          "hi-IN": "मेनू एक्सेस",
          "kn-IN": "ಮೆನು ಪ್ರಾಪ್ತಿ",
          "ml-IN": "മെനു ആക്‌സസ്",
          "ta-IN": "மெனு அணுகல்",
          "te-IN": "మెనూ యాక్సెస్",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/menu/roles",
        icon: "CircleUser",
        id: "ADMIN_MENU_ROLE",
        menuId: "ADMIN_MENU",
        name: "Roles",
        nameLang: {
          "en-US": "Roles",
          "hi-IN": "भूमिकाएँ",
          "kn-IN": "ಪಾತ್ರಗಳು",
          "ml-IN": "റോളുകൾ",
          "ta-IN": "பாத்திரங்கள்",
          "te-IN": "పాత్రలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
    ],
    icon: "Menu",
    id: "ADMIN_MENU",
    name: "Menu",
    nameLang: {
      "en-US": "Menu",
      "hi-IN": "मेनू",
      "kn-IN": "ಮೆನು",
      "ml-IN": "മെനു",
      "ta-IN": "மெனு",
      "te-IN": "మెనూ",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/horoscope/zodiac-signs",
        icon: "Circle",
        id: "ADMIN_HOROSCOPE_ZODIAC_SIGNS",
        menuId: "ADMIN_HOROSCOPE",
        name: "Zodiac Signs",
        nameLang: {
          "en-US": "Zodiac Signs",
          "hi-IN": "राशियाँ",
          "kn-IN": "ರಾಶಿಚಕ್ರಗಳು",
          "ml-IN": "രാശികൾ",
          "ta-IN": "இராசிகள்",
          "te-IN": "రాశులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/horoscope/daily",
        icon: "Sun",
        id: "ADMIN_HOROSCOPE_DAILY",
        menuId: "ADMIN_HOROSCOPE",
        name: "Daily",
        nameLang: {
          "en-US": "Daily",
          "hi-IN": "दैनिक",
          "kn-IN": "ದೈನಂದಿನ",
          "ml-IN": "ദൈനംദിനം",
          "ta-IN": "தினசரி",
          "te-IN": "రోజువారీ",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/horoscope/weekly",
        icon: "Calendar",
        id: "ADMIN_HOROSCOPE_WEEKLY",
        menuId: "ADMIN_HOROSCOPE",
        name: "Weekly",
        nameLang: {
          "en-US": "Weekly",
          "hi-IN": "साप्ताहिक",
          "kn-IN": "ವಾರದ",
          "ml-IN": "ആഴ്ചതോറും",
          "ta-IN": "வாராந்திர",
          "te-IN": "వారాంతపు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/horoscope/monthly",
        icon: "CalendarDays",
        id: "ADMIN_HOROSCOPE_MONTHLY",
        menuId: "ADMIN_HOROSCOPE",
        name: "Monthly",
        nameLang: {
          "en-US": "Monthly",
          "hi-IN": "मासिक",
          "kn-IN": "ಮಾಸಿಕ",
          "ml-IN": "മാസിക",
          "ta-IN": "மாதாந்திர",
          "te-IN": "నెలసరి",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 4,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/horoscope/yearly",
        icon: "BookOpen",
        id: "ADMIN_HOROSCOPE_YEARLY",
        menuId: "ADMIN_HOROSCOPE",
        name: "Yearly",
        nameLang: {
          "en-US": "Yearly",
          "hi-IN": "वार्षिक",
          "kn-IN": "ವಾರ್ಷಿಕ",
          "ml-IN": "വാർഷികം",
          "ta-IN": "ஆண்டு",
          "te-IN": "ఏటా",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 5,
        type: "ADMIN",
      },
    ],
    icon: "Star",
    id: "ADMIN_HOROSCOPE",
    module: "ADMIN_HOROSCOPE",
    name: "Horoscope",
    nameLang: {
      "en-US": "Horoscope",
      "hi-IN": "राशिफल",
      "kn-IN": "ರಾಶಿಭವಿಷ್ಯ",
      "ml-IN": "ജാതകം",
      "ta-IN": "ஜாதகம்",
      "te-IN": "రాశిఫలాలు",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/auspicious/names",
        icon: "FileText",
        id: "ADMIN_AUSPICIOUS_NAMES",
        menuId: "ADMIN_AUSPICIOUS",
        name: "Names",
        nameLang: {
          "en-US": "Names",
          "hi-IN": "नाम",
          "kn-IN": "ಹೆಸರುಗಳು",
          "ml-IN": "പേരുകൾ",
          "ta-IN": "பெயர்கள்",
          "te-IN": "పేర్లు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/auspicious/timings",
        icon: "Clock",
        id: "ADMIN_AUSPICIOUS_TIMINGS",
        menuId: "ADMIN_AUSPICIOUS",
        name: "Timings",
        nameLang: {
          "en-US": "Timings",
          "hi-IN": "समय",
          "kn-IN": "ಸಮಯಗಳು",
          "ml-IN": "സമയം",
          "ta-IN": "நேரம்",
          "te-IN": "సమయాలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
    ],
    icon: "Sun",
    id: "ADMIN_AUSPICIOUS",
    module: "ADMIN_AUSPICIOUS",
    name: "Auspicious",
    nameLang: {
      "en-US": "Auspicious",
      "hi-IN": "शुभ",
      "kn-IN": "ಶುಭ",
      "ml-IN": "ശുഭ",
      "ta-IN": "சுப",
      "te-IN": "శుభం",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/services/poojas",
        icon: "Flower2",
        id: "ADMIN_SERVICES_POOJAS",
        menuId: "ADMIN_SERVICES",
        name: "Poojas",
        nameLang: {
          "en-US": "Poojas",
          "hi-IN": "पूजा",
          "kn-IN": "ಪೂಜೆಗಳು",
          "ml-IN": "പൂജകൾ",
          "ta-IN": "பூஜைகள்",
          "te-IN": "పూజలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
    ],
    icon: "Briefcase",
    id: "ADMIN_SERVICES",
    module: "ADMIN_SERVICES",
    name: "Services",
    nameLang: {
      "en-US": "Services",
      "hi-IN": "सेवाएं",
      "kn-IN": "ಸೇವೆಗಳು",
      "ml-IN": "സേവനങ്ങൾ",
      "ta-IN": "சேவைகள்",
      "te-IN": "సేవలు",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/activities/mantras",
        icon: "Music",
        id: "ADMIN_ACTIVITIES_MANTRAS",
        menuId: "ADMIN_ACTIVITIES",
        name: "Mantras",
        nameLang: {
          "en-US": "Mantras",
          "hi-IN": "मंत्र",
          "kn-IN": "ಮಂತ್ರಗಳು",
          "ml-IN": "മന്ത്രങ്ങൾ",
          "ta-IN": "மந்திரங்கள்",
          "te-IN": "మంత్రాలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/activities/donations",
        icon: "HandHeart",
        id: "ADMIN_ACTIVITIES_DONATIONS",
        menuId: "ADMIN_ACTIVITIES",
        name: "Donations",
        nameLang: {
          "en-US": "Donations",
          "hi-IN": "दान",
          "kn-IN": "ದೇಣಿಗೆಗಳು",
          "ml-IN": "സംഭാവനകൾ",
          "ta-IN": "நன்கொடைகள்",
          "te-IN": "విరాళాలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/activities/poojas",
        icon: "Flower2",
        id: "ADMIN_ACTIVITIES_POOJAS",
        menuId: "ADMIN_ACTIVITIES",
        name: "Poojas",
        nameLang: {
          "en-US": "Poojas",
          "hi-IN": "पूजा",
          "kn-IN": "ಪೂಜೆಗಳು",
          "ml-IN": "പൂജകൾ",
          "ta-IN": "பூஜைகள்",
          "te-IN": "పూజలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
    ],
    icon: "Activity",
    id: "ADMIN_ACTIVITIES",
    module: "ADMIN_ACTIVITIES",
    name: "Activities",
    nameLang: {
      "en-US": "Activities",
      "hi-IN": "गतिविधियाँ",
      "kn-IN": "ಚಟುವಟಿಕೆಗಳು",
      "ml-IN": "പ്രവർത്തനങ്ങൾ",
      "ta-IN": "செயல்பாடுகள்",
      "te-IN": "కార్యకలాపాలు",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/reports/users",
        icon: "Users",
        id: "ADMIN_REPORTS_USERS",
        menuId: "ADMIN_REPORTS",
        name: "Users",
        nameLang: {
          "en-US": "Users",
          "hi-IN": "उपयोगकर्ता",
          "kn-IN": "ಬಳಕೆದಾರರು",
          "ml-IN": "ഉപയോക്താക്കൾ",
          "ta-IN": "பயனர்கள்",
          "te-IN": "వినియోగదారులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/reports/astrologers",
        icon: "Star",
        id: "ADMIN_REPORTS_ASTROLOGERS",
        menuId: "ADMIN_REPORTS",
        name: "Astrologers",
        nameLang: {
          "en-US": "Astrologers",
          "hi-IN": "ज्योतिषी",
          "kn-IN": "ಜ್ಯೋತಿಷಿಗಳು",
          "ml-IN": "ജ്യോതിഷികൾ",
          "ta-IN": "ஜோதிடர்கள்",
          "te-IN": "జ్యోతిష్కులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
    ],
    icon: "ChartColumnBig",
    id: "ADMIN_REPORTS",
    module: "ADMIN_REPORTS",
    name: "Reports",
    nameLang: {
      "en-US": "Reports",
      "hi-IN": "रिपोर्ट",
      "kn-IN": "ವರದಿಗಳು",
      "ml-IN": "റിപ്പോർട്ടുകൾ",
      "ta-IN": "அறிக்கைகள்",
      "te-IN": "నివేదికలు",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/settings/subscription-plans",
        icon: "CreditCard",
        id: "ADMIN_SETTINGS_SUBSCRIPTION_PLANS",
        menuId: "ADMIN_SETTINGS",
        name: "Subscription Plans",
        nameLang: {
          "en-US": "Subscription Plans",
          "hi-IN": "सदस्यता योजनाएं",
          "kn-IN": "ಚಂದಾದಾರಿಕೆ ಯೋಜನೆಗಳು",
          "ml-IN": "സബ്സ്ക്രിപ്ഷൻ പ്ലാനുകൾ",
          "ta-IN": "சந்தா திட்டங்கள்",
          "te-IN": "సబ్‌స్క్రిప్షన్ ప్లాన్‌లు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/settings/shipping-charges",
        icon: "Truck",
        id: "ADMIN_SETTINGS_SHIPPING_CHARGES",
        menuId: "ADMIN_SETTINGS",
        name: "Shipping Charges",
        nameLang: {
          "en-US": "Shipping Charges",
          "hi-IN": "शिपिंग शुल्क",
          "kn-IN": "ಸಾಗಾಟ ಶುಲ್ಕ",
          "ml-IN": "ഷിപ്പിംഗ് ചാർജുകൾ",
          "ta-IN": "கப்பல் கட்டணங்கள்",
          "te-IN": "రవాణా ఖర్చులు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/settings/notifications",
        icon: "Bell",
        id: "ADMIN_SETTINGS_NOTIFICATIONS",
        menuId: "ADMIN_SETTINGS",
        name: "Notifications",
        nameLang: {
          "en-US": "Notifications",
          "hi-IN": "सूचनाएं",
          "kn-IN": "ಅಧಿಸೂಚನೆಗಳು",
          "ml-IN": "അറിയിപ്പുകൾ",
          "ta-IN": "அறிவிப்புகள்",
          "te-IN": "నోటిఫికేషన్‌లు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 3,
        type: "ADMIN",
      },
    ],
    icon: "Settings",
    id: "ADMIN_SETTINGS",
    module: "ADMIN_SETTINGS",
    name: "Settings",
    nameLang: {
      "en-US": "Settings",
      "hi-IN": "सेटिंग्स",
      "kn-IN": "ಸಂಯೋಜನೆಗಳು",
      "ml-IN": "ക്രമീകരണങ്ങൾ",
      "ta-IN": "அமைப்புகள்",
      "te-IN": "సెట్టింగ్స్",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/support/contact-us",
        icon: "Phone",
        id: "ADMIN_SUPPORT_CONTACT_US",
        menuId: "ADMIN_SUPPORT",
        name: "Contact Us",
        nameLang: {
          "en-US": "Contact Us",
          "hi-IN": "संपर्क करें",
          "kn-IN": "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
          "ml-IN": "ബന്ധപ്പെടുക",
          "ta-IN": "எங்களை தொடர்பு கொள்ளவும்",
          "te-IN": "మమ్మల్ని సంప్రదించండి",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
    ],
    icon: "Headset",
    id: "ADMIN_SUPPORT",
    module: "ADMIN_SUPPORT",
    name: "Support",
    nameLang: {
      "en-US": "Support",
      "hi-IN": "सहायता",
      "kn-IN": "ಬೆಂಬಲ",
      "ml-IN": "പിന്തുണ",
      "ta-IN": "ஆதரவு",
      "te-IN": "మద్దతు",
    },
    type: "ADMIN",
  },
  {
    active: true,
    children: [
      {
        active: true,
        href: "/application-data/testimonials",
        icon: "Quote",
        id: "ADMIN_APPLICATION_DATA_TESTIMONIALS",
        menuId: "ADMIN_APPLICATION_DATA",
        name: "Testimonials",
        nameLang: {
          "en-US": "Testimonials",
          "hi-IN": "प्रशंसापत्र",
          "kn-IN": "ಸಾಕ್ಷ್ಯಗಳು",
          "ml-IN": "സാക്ഷ്യങ്ങൾ",
          "ta-IN": "சான்றுகள்",
          "te-IN": "ప్రశంసలు",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 1,
        type: "ADMIN",
      },
      {
        active: true,
        href: "/application-data/site-info",
        icon: "Globe",
        id: "ADMIN_APPLICATION_DATA_SITE_INFO",
        menuId: "ADMIN_APPLICATION_DATA",
        name: "Site Info",
        nameLang: {
          "en-US": "Site Info",
          "hi-IN": "साइट जानकारी",
          "kn-IN": "ಸೈಟ್ ಮಾಹಿತಿ",
          "ml-IN": "സൈറ്റ് വിവരം",
          "ta-IN": "தளத் தகவல்",
          "te-IN": "సైట్ సమాచారం",
        },
        permissions: { create: true, delete: true, read: true, update: true },
        priority: 2,
        type: "ADMIN",
      },
    ],
    icon: "Database",
    id: "ADMIN_APPLICATION_DATA",
    module: "ADMIN_APPLICATION_DATA",
    name: "Application Data",
    nameLang: {
      "en-US": "Application Data",
      "hi-IN": "एप्लिकेशन डेटा",
      "kn-IN": "ಅನ್ವಯ ಡೇಟಾ",
      "ml-IN": "അപ്ലിക്കേഷൻ ഡാറ്റ",
      "ta-IN": "பயன்பாட்டு தரவு",
      "te-IN": "అప్లికేషన్ డేటా",
    },
    type: "ADMIN",
  },
];
